### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by elyssial** [MatrixDJ96/EZBlocker2#18]
[EZBlocker2.log](https://github.com/MatrixDJ96/EZBlocker2/files/2358977/EZBlocker2.log)

Also says "Spotify is in private session" even though it isn't.

**Comment by Eki474** [comment]
Hi, 

I have the same problem. After the authentication in the browser where I do not see the "Authorization Successful" screen, EZBlocker2 is hanging because "Spotify is in private session" even though it isn't. My log are different from elyssial though, I have a "Too many request" error (429). I tried Uninstalling Spotify, removing EZBlocker2 and cleaning the hosts file to install everything from scratch but it doesn't change anything. My log file is attached. 

Also I sometimes got the "Authorization Successful" screen but it doesn't block any add and if I activate the "mute adds" it just mutes half the add to end in a crash after some time. 

[EZBlocker2-log.txt](https://github.com/MatrixDJ96/EZBlocker2/files/2369724/EZBlocker2-log.txt)

If you could help out with this it would be really great.

**Comment by MatrixDJ96** [comment]
Thank you for reporting this.
I'll check asap

**Comment by Eki474** [comment]
I took a screen shot of the error message, if it can help 
![capture](https://user-images.githubusercontent.com/9626260/45649424-8d817880-bacb-11e8-939f-92b5e590ed63.PNG)
